// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/convocatories": StaticRoute;
    "/dashboard/entrenadors": StaticRoute;
    "/dashboard/entrenadors/[id]": StaticRoute;
    "/dashboard/equips/entrenadors": StaticRoute;
    "/dashboard/equips": StaticRoute;
    "/dashboard/equips/[id]": StaticRoute;
    "/dashboard/inscripciones": StaticRoute;
    "/dashboard/inscripciones/[id]": StaticRoute;
    "/dashboard/jugadors/crear": StaticRoute;
    "/dashboard/jugadors": StaticRoute;
    "/dashboard/jugadors/[id]/editar": StaticRoute;
    "/dashboard/noticies/crear": StaticRoute;
    "/dashboard/noticies": StaticRoute;
    "/dashboard/noticies/[id]/editar": StaticRoute;
    "/dashboard": StaticRoute;
    "/dashboard/patrocinadors/crear": StaticRoute;
    "/dashboard/patrocinadors": StaticRoute;
    "/dashboard/resultats": StaticRoute;
    "/demo": StaticRoute;
    "/inscripcio": StaticRoute;
    "/my-club": StaticRoute;
    "/noticies": StaticRoute;
    "/noticies/[slug]": StaticRoute;
    "/pagaments/confirmacio": StaticRoute;
    "/pagaments": StaticRoute;
    "/": StaticRoute;
    "/resultats": StaticRoute;
  }
}
